Description of ExampleInfill
ExampleInfill
PURPOSE
% Example of use of the enrichment of IHS
SYNOPSIS
This is a script file.
DESCRIPTION
% Example of use of the enrichment of IHS
 L. LAURENT -- 06/01/2014 -- luc.laurent@lecnam.net
CROSS-REFERENCE INFORMATION
This function calls:
initDirMultiDOE % Initialization of the directories (MATLAB's path)
addSampleDOE % Function for adding new points in an existing sampling
initDOE % Initialization on the DOE structure (definition of the options)
buildDOE % Building sampling
This function is called by:
SOURCE CODE
%% Example of use of the enrichment of IHS
% L. LAURENT -- 06/01/2014 -- luc.laurent@lecnam.net
%initialize folders of the toolbox
initDirMultiDOE;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%load configuration
doe=initDOE(3);
%
doe.Xmin=[-1 -2 -3];
doe.Xmax=[3 2 1];
doe.type='IHS_R'; %or LHS_R
doe.ns=5;
doe.sort.on=false; %w/o sorting
doe.disp=true;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%build DOE
sampling=buildDOE(doe);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%enrichment
doe.ns=2;
newSample=addSampleDOE(sampling,doe);
dispDOE(newSample,doe)