Description of ajout_tir_doe
ajout_tir_doe
PURPOSE
% Fonction assurant l'enrichissement de la base de points echantillonnes
SYNOPSIS
function new_tir=ajout_tir_doe(old_tirages,doe)
DESCRIPTION
% Fonction assurant l'enrichissement de la base de points echantillonnes
% L. LAURENT -- 04/12/2011 -- laurent@lmt.ens-cachan.fr
CROSS-REFERENCE INFORMATION
This function calls:
ihs_R % Generation de plan d'experience LHS a partir de R (avec pretirage de LHS enrichi)
lhsu_R % Generation de plan d'experience LHS a partir de R (avec pretirage de LHS enrichi)
This function is called by:
EXEMPLE_ENRICHISSEMENT Exemple d'enrichissement tirage LHS_R
SOURCE CODE
%% Fonction assurant l'enrichissement de la base de points echantillonnes
%% L. LAURENT -- 04/12/2011 -- laurent@lmt.ens-cachan.fr
% l'enrichissement necessite la presence du package 'R.matlab' dans R
function new_tir=ajout_tir_doe(old_tirages,doe)
Xmin=doe.Xmin;
Xmax=doe.Xmax;
nb_samples=doe.nb_samples;
% en fonction du type de tirages initial
switch doe.type
    case 'LHS_R'
        [new_tir]=lhsu_R(Xmin,Xmax,nb_samples,old_tirages);
    case 'IHS_R'
        [new_tir]=ihs_R(Xmin,Xmax,nb_samples,old_tirages);
    otherwise
        fprintf('>>>> Seul les tirages de type LHS_R et IHS_R \n permettent l''enrichissement\n')
        pts=[];
end