Description of init_rep_LMTir
init_rep_LMTir
PURPOSE
% Script d'ajout des chemins de la Toolbox LMTir
SYNOPSIS
function doss=init_rep_LMTir(chemin)
DESCRIPTION
% Script d'ajout des chemins de la Toolbox LMTir
% L. LAURENT -- 06/01/2014 -- laurent@lmt.ens-cachan.fr
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
EXEMPLE_ENRICHISSEMENT Exemple d'enrichissement tirage LHS_R
EXEMPLE_UTILISATION Exemple d'utilisation de la Toolbox LMTir
gene_doc % Generation de la documentation (grace a m2html)
SOURCE CODE
%% Script d'ajout des chemins de la Toolbox LMTir
%% L. LAURENT -- 06/01/2014 -- laurent@lmt.ens-cachan.fr
function doss=init_rep_LMTir(chemin)
%dossier de la Toolbox LMTir
doss={'routines','routines/divers',...
    'routines/libs','routines/libs/m2html',...
    'tirages','tirages/IHS','tirages/LHS'};
%si pas de chemin spécifié
if nargin==0
    chemin=pwd;
end
%chemins absolus
chemin_full=cellfun(@(c)[chemin '/' c],doss,'uni',false);
%ajout au PATH
cellfun(@addpath,chemin_full);