Description of ihs_test
ihs_test
PURPOSE
*****************************************************************************80
SYNOPSIS
function ihs_test ()
DESCRIPTION
*****************************************************************************80
% IHS_TEST tests the IHS library.
  Licensing:
    This code is distributed under the GNU LGPL license.
  Modified:
    16 May 2011
  Author:
    John Burkardt
CROSS-REFERENCE INFORMATION
This function calls:
ihs_test01 *****************************************************************************80
ihs_test02 *****************************************************************************80
ihs_test03 *****************************************************************************80
ihs_test04 *****************************************************************************80
timestamp *****************************************************************************80
This function is called by:
ihs_test_output
SOURCE CODE
function ihs_test ()
%*****************************************************************************80
%
%% IHS_TEST tests the IHS library.
%
%  Licensing:
%
%    This code is distributed under the GNU LGPL license.
%
%  Modified:
%
%    16 May 2011
%
%  Author:
%
%    John Burkardt
%
  timestamp ( );
  fprintf ( 1, '\n' );
  fprintf ( 1, 'IHS_TEST\n' );
  fprintf ( 1, '  MATLAB version\n' );
  fprintf ( 1, '  Test the IHS library.\n' );
  ihs_test01 ( );
  ihs_test02 ( );
  ihs_test03 ( );
  ihs_test04 ( );
%
%  Terminate.
%
  fprintf ( 1, '\n' );
  fprintf ( 1, 'IHS_TEST\n' );
  fprintf ( 1, '  Normal end of execution.\n' );
  fprintf ( 1, '\n' );
  timestamp ( );
  return
end