Description of ranking
ranking
PURPOSE
[r,i]=ranking(x)
SYNOPSIS
function [r,i]=ranking(x)
DESCRIPTION
 [r,i]=ranking(x)
 Ranking of a vector
 input:
   x   : vector (nrow,1)
 output:
 r : rank of the vector  (nrow,1)
 i : index vector from the sort routine  (nrow,1)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
lhs_iman z=lhs_iman(xmean,xsd,corr,nsample,nloop)
lhs_iman_n z=lhs_iman_n(xmean,xsd,corr,nsample,ntry)
rank_corr rc=rank_corr(corr,nsample)
SOURCE CODE
function [r,i]=ranking(x)
% [r,i]=ranking(x)
% Ranking of a vector
% input:
%   x   : vector (nrow,1)
% output:
% r : rank of the vector  (nrow,1)
% i : index vector from the sort routine  (nrow,1)
%
n=length(x);
[s,i]=sort(x);
r(i,1)=[1:n]';